version: '3.8'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data